apiVersion: v1
kind: Service
metadata:
  name: proxy-service2-http1
spec:
  ports:
  - port: 8080
    targetPort: 11095
  selector:
    app: client
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service2-http3
spec:
  ports:
  - port: 8443
    targetPort: 11096
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      initContainers:
      - name: init-networking
        image: tolgaomeratalay/init:1.2
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      containers:
      - name: application
        image: tolgaomeratalay/http1client:1.0
      - name: proxy
        image: tolgaomeratalay/biproxy:1.8
        #command:
        #  - /bin/sleep
        #  - infinity
        ports:
        - containerPort: 11095
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
