apiVersion: v1
kind: Service
metadata:
  name: proxy-service-http1
spec:
  ports:
  - port: 8080
    targetPort: 11095
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service-http3
spec:
  ports:
  - port: 443
    targetPort: 11096
  selector:
    app: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      initContainers:
      - name: init-networking
        image: tolgaomeratalay/init:1.1
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      containers:
      - name: application
        image: tolgaomeratalay/http1server:1.0
      - name: proxy
        image: tolgaomeratalay/httpproxy:1.3
        ports:
        - containerPort: 11095
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
